accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',  views.UserSignupView.as_view(), name='ajax_signup'),
    path('login/',  views.UserLoginView.as_view(), name='ajax_login'),
    path('logout/',  views.UserLogoutView.as_view(), name='logout'),
]

book_reviews/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'book_reviews'

urlpatterns = [
    path('datasource/', views.DataTableSourceView.as_view(),
         name='datasource'),
    path('detail/', views.ReviewDetailView.as_view(),
         name='review_details'),
    path('edit/', login_required(views.ReviewDetailView.as_view()),
         name='review_edit'),
    path('add/', login_required(views.ReviewAddView.as_view()),
         name='review_add'),
]

lq_reviews/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from book_reviews.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home_page'),
    path('reviews/', include('book_reviews.urls'), name='book_reviews'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/aa.html
<!-- Signup Modal -->
  <div class="modal fade" id="SignupModalXX" role="dialog">
     <div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header" style="padding:35px 50px;">
      <h5 class="modal-title">Sign Up</h5>
      <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body" style="padding:40px 50px;">
      <form role="form">
        <div class="form-group">
          <label for="usrname"><img src="/static/icons/person-fill.svg"> Username</label>
          <input type="text" class="form-control" id="usrname" placeholder="Enter email">
        </div>
        <div class="form-group">
          <label for="psw"><img src="/static/icons/eye-slash.svg"> Password</label>
          <input type="text" class="form-control" id="psw" placeholder="Enter password">
        </div>
          <div class="form-group">
          <label for="psw"><img src="/static/icons/eye-slash.svg"> Re-enter Password</label>
          <input type="text" class="form-control" id="psw" placeholder="Enter password">
        </div>

      </form>
    </div>
    <div class="modal-footer">
      <button type="submit" class="btn btn-success btn-block">
          <img style="fill: greenyellow;" src="/static/icons/power.svg" />
          Login
      </button>
      <button type="submit" class="btn btn-danger btn-default" data-bs-dismiss="modal">Cancel</button>
      <a href="#">Sign Up</a>
    </div>
  </div>
     </div>
  </div>
<!-- end of signup modal -->

templates/home.html
{% extends "main_base.html" %}

{% block extra_style %}
    <style>
    .a-btn {
        background-color: lightgoldenrodyellow;;
        color: #565221;
        border: 1px solid lightslategray;
        border-radius: 4px;
    }

    .s-title {
        font-size: 0.9em;
        font-weight: bold;
    }

    .review-summary {
        margin-top: 5px;
    }

    .review-summary img {
        float:left;
        width: 80px;
        height:80px;
        object-fit: contain;
        margin: 0 15px 15px 0;
    }

    #searchResult th {
        font-size: 0.9em;
    }

    #searchResult td {
        font-size: 0.8em;
    }

    .dt-paging-button {
        font-size: 0.8em;
    }

    .dt-search {
        font-size: 0.8em;
    }

    </style>
{% endblock %}


{% block main %}

    <!-- start tab contents -->
    <div class="tab-content">

    <!-- nav-home tab -->
        <div class="tab-pane fade  show active" id="nav-home" role="tabpanel">

            <div class="row"  style="min-height: 800px;">
<div class="col-sm-7">
    <div class="m-3 border p-3">
        <div id="reviewDetail">
            Select a review from the Summary List
        </div>
        <div id="viewDetail" style="display: none">
            Details will be here
        </div>
    </div>
</div>
<div class="col-sm-5">
    <div class="m-3">
        <div class="row">
            <div class="col-8">
                <h5 class="pb-0 mb-0">Search Reviews</h5>
                <!-- checkbox for search self reviews, only shown for login users -->
                {% if request.user.is_authenticated %}
                    <div class="control-group pt-1" style="font-size: small;">
                        <label for="searchSelf" class="control px-2">
                            Self Only
                        </label>
                        <input type="checkbox"  class="control" id="searchSelf" />
                    </div>

                    </div>
                    <div class="col-3">
                        <button class="btn btn-sm btn-danger float-end" id="reviewAddBtn">Add New</button>
                    </div>
                {% endif %}
        </div>
        <div class="row"><div class="col-11"><hr /></div></div>

        <div class="row mt-0">
            <div style="width: 95%">
                <table id="searchResult" class="display" style="width: 100%">
                    <thead>
                    <tr>
                        <th>
                            Review Summary List
                        </th>
                        <th> </th>   <!-- this is for detail button with no column header -->
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>

        <div>
            <div class="pt-3 pb-2">
                <h6>Recent Reviews</h6>
            </div>

            <div id="recentReviewDiv">
                {% for review in recent_list %}
                <div class="row">
                    <div class="review-summary">
                        <img src="{{ review.0 }}" class="pe-3 b-btn" data-id="{{ review.4 }}" alt="review photo"/>
                        <ul>
                            <li>{{ review.1 }}</li>
                            <li>{{ review.2 }}</li>
                            <li>{{ review.3 }}</li>
                        </ul>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>


</div>
</div>
    <!----------------------------------------- end of nav-home -->
        </div>

    <!-- nav-tab myreviews -->
        <div class="tab-pane fade" id="nav-myreviews" role="tabpanel">
            <div class="row"  style="min-height: 800px;">
                <div class="col">
                    <h3>Hello MyView Tab!!!</h3>
                </div>
            </div>

    <!------------------------------------- end of nav-myreviews -->
        </div>

    <!------------------------------------ end of nav-tabContent -->
    </div>

{% endblock %}

{% block perpage_script %}
    <script>
        let searchResultTable;

        function render_summary(review, type) {
            if (type === 'display') {
                return `<ul><li>${review[3]}</li><li>Title: ${review[4]}</li><li>Blurb: ${review[1]}</li><li>Review: ${review[5]}</li></ul>`
            } else {
                return review
            }
        }

        function render_button(review_id, type) {
            if (type === 'display') {
                return "<button class='a-btn' data-id='" +
                    review_id + "'>" +
                    '<img src="/static/icons/zoom-in.svg"><img>' + "</button>"
            } else {
                return review_id
            }
        }

        $(function() {

            // init dt
            searchResultTable = $("#searchResult").DataTable({
                {#data: dataSet,#}
                ajax: {
                    url: "{% url 'book_reviews:datasource' %}",
                    type: 'GET',
                    dataSrc: ''
                },
                columnDefs: [
                    {
                        target: 0,
                        visible: true,
                        render: render_summary,
                    },
                    {
                        target: 1,
                        visible: true,
                        width: '30px',
                        render: render_button,
                    }
                ],
                paging: true,
                pageLength: 4,
                length_menu: false,
                info: false,
                ordering: false,
                layout: {
                    topStart: null
                },
            });

            searchResultTable.on("click", ".a-btn", detail_display);

            recentReviewDiv = $("#recentReviewDiv");
            recentReviewDiv.on("click", ".b-btn", detail_display);

            $(document).on("click", "#reviewAddBtn", reviewAdd);
            $(document).on("click", "#reviewSubmitBtn", reviewEditSubmit);
            $(document).on("click", "#reviewCancelBtn", reviewEditCancel);

            $(document).on("click", "#reviewAddCancelBtn", reviewAddCancel);

        });

    </script>

{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="BookReview Site">
    <meta name="author" content="Leon Qu">
 
    <title>Book Review Site</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
          crossorigin="anonymous">

          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body>
    
<header>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Book Reviews</a>

      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Reviews</a>
          </li>
        </ul>
      </div>

      <div class="d-flex px-2 px-sm-4">
        <span class="navbar-text px-2 px-md-4">Hello User!</span>
        <button class="btn btn-outline-success" type="submit">Login</button>
      </div>

    </div>
  </nav>

  <div class="container-fluid px-0">
    <img src="/static/images/top_img_wide.png" style="width: 100%;">
  </div>
</header>

<main>
  <div  style="height: 1000px;">

  </div>
</main>

<footer class="text-center p-3 fixed-bottom footer  bg-success bg-gradient">
 <span class="text-light">&copy;2024 Copyright</span> <span class="px-3 fs-5" style="color: antiquewhite;">Leon Qu</span>
</footer>
      
</body>
</html>

templates/main_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="BookReview Site">
    <meta name="author" content="Leon Qu">

    <title>Book Review Site</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- jQuery and plugins -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.css" />
    <script src="https://cdn.datatables.net/2.0.2/js/dataTables.js"></script>

    <script src="/static/js/users.js"></script>
    <script src="/static/js/reviews.js"></script>

  <style>
      .signup-header, h4, .close {
        background-color: #5cb85c;
        color:white !important;
        text-align: center;
        font-size: 30px;
      }
      .login-header, h4, .close {
        background-color: #3e8fea;
        color:white !important;
        text-align: center;
        font-size: 30px;
      }
      .modal-footer {
        background-color: #f9f9f9;
      }
  </style>

    {% block extra_style %}{% endblock %}
    {% block extra_script %}{% endblock %}

  </head>

<body>

<header>

  <nav  id="topNavbar" class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Book Reviews</a>

      <div class="collapse navbar-collapse">
            <ul class="nav nav-tab me-auto mb-2 mb-lg-0" role="tablist" id="navBarItems">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="nav-home-tab" data-bs-toggle="tab"
                       data-bs-target="#nav-home" role="tab" style="color: white" href="#">
                        Home
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="nav-myreviews-tab" data-bs-toggle="tab"
                       data-bs-target="#nav-myreviews" role="tab" style="color: white" href="#">
                        My Reviews
                    </a>
                </li>
                {% endif %}
            </ul>
      </div>

      <div class="d-flex px-2 px-sm-4">
        {% if request.user.is_authenticated %}
            <span class="navbar-text px-2 px-md-4">
            <span class="px-3" style="font-weight: bold; color: #16de30;">
                Hello {{ request.user.username }} !</span>
            <a class="btn btn-outline-success" href="{% url 'accounts:logout' %}">Logout</a>
        </span>
        {% else %}
            <button id="signup" class="btn btn-outline-success">Sign Up</button>
            <div style="margin-left: 10px;">
                <button id="loginPopup" class="btn btn-outline-success">
                    Login
                </button></div>
        {% endif %}
      </div>

    </div>
  </nav>

    <!-- give enough space for the area covered by the fixed header  -->
    <div class="row" style="min-height: 50px"></div>

    <!-- hidden input for passing info to external js file -->
    <input type="hidden" id="login-url"
           data-url="{% url 'accounts:ajax_login'  %}" />
    <input type="hidden" id="signup-url"
           data-url="{% url 'accounts:ajax_signup'  %}" />
    <input type="hidden" id="searchTable-url"
           data-url="{% url 'book_reviews:datasource' %}" />
    <input type="hidden" id="detail-base-url"
           data-url="{% url 'book_reviews:review_details' %}" />

  <div class="container-fluid px-0">
    <img src="/static/images/top_img_wide.png" style="width: 100%;" alt="top image" />
  </div>
</header>

<main>

{% block main %}{% endblock %}

    <!-- give enough space for the area covered by the fixed footer -->
    <div class="row" style="min-height: 50px"></div>

<!-- Login Modal -->
    <div class="modal fade" id="LoginModal" role="dialog">
        <div class="modal-dialog">

  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header login-header" style="padding:35px 50px;">
      <h5 class="modal-title">Login</h5>
      <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body" style="padding:40px 50px;">
      <form role="form">
        <div class="form-group">
          <label for="loginUsername" class="pb-1">
              <img src="/static/icons/person-fill.svg" alt="username icon" />
              Username
          </label>
          <input type="text" class="form-control" id="loginUsername" placeholder="Enter email">
        </div>
        <div class="form-group">
          <label for="loginPwd" class="pb-1 pt-3">
              <img src="/static/icons/eye-slash.svg" alt="password icon" />
              Password
          </label>
          <input type="password" class="form-control" id="loginPwd" placeholder="Enter password">
        </div>
      </form>
    </div>
    <div class="modal-footer">
      <button id="loginButton" class="btn btn-primary btn-block">
          Login
      </button>
      <button type="submit" class="btn btn-danger btn-default" data-bs-dismiss="modal">Cancel</button>
    </div>
  </div>
        </div>
    </div>
<!-- end of login modal -->

<!-- Signup Modal -->
  <div class="modal fade" id="SignupModal" role="dialog">
     <div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header signup-header" style="padding:35px 50px;">
      <h5 class="modal-title">Sign Up</h5>
      <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal"></button>
    </div>
    <div class="modal-body" style="padding:40px 50px;">
      <form role="form">
        <div class="form-group">
          <label for="su_username" class="pb-1">
              <img src="/static/icons/person-fill.svg" alt="username icon" />
              Username
          </label>
          <input type="text" class="form-control" id="su_username"
                 name="su_username" placeholder="4 chars or longer">
        </div>
        <div class="form-group">
          <label for="su_pwd_1" class="pb-1 pt-3">
              <img src="/static/icons/eye-slash.svg" alt="password icon">
              Password</label>
          <input type="password" class="form-control" name="su_pwd_1"
                 id="su_pwd_1" placeholder="password - 4 char or longer">
        </div>
          <div class="form-group">
          <label for="su_pwd_2" class="pb-1 pt-3">
              <img src="/static/icons/eye-slash.svg" alt="password icon">
              Re-enter Password
          </label>
          <input type="password" class="form-control" name="su_pwd_2"
                 id="su_pwd_2" placeholder="repeat the same password">
        </div>

      </form>
    </div>
    <div class="modal-footer">
      <button id="signupButton" class="btn btn-success btn-block">
          Sign Up
      </button>
      <button class="btn btn-danger btn-default" data-bs-dismiss="modal">Cancel</button>
    </div>
  </div>
     </div>
  </div>
<!-- end of Signup modal -->

</main>

<footer class="text-center p-3 fixed-bottom footer  bg-success bg-gradient">
    <span class="text-light">&copy;2024 Copyright</span>
    <span class="px-3 fs-5" style="color: antiquewhite;">Leon Qu</span>
</footer>

{% block perpage_script %}{% endblock %}

</body>
</html>

templates/review_add_div.html
<form id="reviewAddForm" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row form-group">
        {{ form }}
    </div>

    <div class="pt-5">
        <button type="submit" class="control btn btn-sm btn-primary">
            Add</button>
        <button class="control btn btn-sm btn-warning" id="reviewAddCancelBtn">
            Cancel</button>
</div>
</form>
<script>
    $("#reviewAddForm").submit(function(e) {
        e.preventDefault();
        $.ajax({
            url: "{% url 'book_reviews:review_add' %}",
            type: "post",
            data: new FormData(this),
            dataType: "json",
            processData: false,
            contentType: false,
            success: function(data) {
                // alert("Review has been successfully added. " + data.id);
                detail_display("view", data.id);
                // reload dt table
                reloadDT();
            },
        });
    });
</script>

templates/review_display_div.html
<div>
    <div class="row">
        <div class="col-5">
            <img src="{{ review.photo.url }}"
                 style="object-fit: contain; width: 100%; height: 300px;" alt="review photo" />
        </div>
        <div class="col-7 pt-3">
            <div class="d-flex">
                <h5>{{ review.name }}</h5><span  class="ps-2 pt-1" style="font-size: 0.8em;">${{ review.cost }}</span>
            </div>
            <div class="py-2">
                <h6>Description:</h6>
                <p style="font-size: 0.9em">{{ review.blurb }}</p>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <hr style="width:90%" />
    </div>
    <div class="row">
        <div class="col">
            <h5>Review
                <small style="font-size: 0.7em; font-weight: normal;">
                    (published: {{ review.date }})
                </small>
            </h5>

            <p style="font-weight: lighter;">{{ review.review }}</p>
        </div>
    </div>

    {% if can_edit %}
    <div class="row d-flex justify-content-center pt-3">
        <hr style="width:90%" />
    </div>
    <div class="row">
        <div class="col">
            <button id="reviewEditBtn" class="btn btn-small btn-primary"
                    onclick="reviewEdit({{ review.id }})">
                Edit
            </button>
        </div>
    </div>
    {% endif %}
</div>

templates/review_edit_div.html
<form>
    <div class="row">
        <div class="col-5">
            <img src="{{ review.photo.url }}"
                 style="object-fit: contain; width: 100%; height: 300px;" alt="review photo" />
        </div>
        <div class="col-7 pt-3">
            <div class="d-flex">
                <h5>{{ review.name }}</h5><span  class="ps-2 pt-1" style="font-size: 0.8em;">${{ review.cost }}</span>
            </div>
            <div class="py-2">
                <h6>Description:</h6>
                <textarea class="form-control" id="reviewEditBlurb"
                          style="min-width: 100%; min-height: 230px;
                          max-height: 230px; font-size: 0.9em">{{ review.blurb }}</textarea>
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <hr style="width:90%" />
    </div>
    <div class="row">
        <div class="col">
            <h5>Review
                <small style="font-size: 0.7em; font-weight: normal;">
                    (published: {{ review.date }})
                </small>
            </h5>
            <textarea class="form-control" id="reviewEditReview"
                      style="font-weight: lighter; min-width: 100%;
                      min-height: 200px; max-height: 400px;">{{ review.review }}</textarea>
        </div>
    </div>

    {% if can_edit %}
    <div class="row d-flex justify-content-center pt-3">
        <hr style="width:90%" />
    </div>
    <div class="row">
        <div class="col control-group">
            <button id="reviewSubmitBtn" class="btn btn-small btn-primary"
                    data-id="{{ review.id }}">
                Submit
            </button>
            <button id="reviewCancelBtn" class="btn btn-small btn-warning"
                    data-id="{{ review.id }}">
                Cancel
            </button>
        </div>
    </div>
    {% endif %}
</form>